
spring:
  datasource:
    url: "jdbc:h2:file:./vendor-machine;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092"
    username: sa
    password:
    hikari:
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default


flyway:
  enabled: true
  clean-on-validation-error: true
  locations: classpath:/db/migration/
  create-schemas: true
  schemas: vendormachine
  user: sa
  password:
  h2:
    console:
      enabled: true
      path: /h2

